# "For splits, the unified .conf file only works when used along with an existing board/shield you're using from a config repo.
# Put it in the left and right config files for your out of tree shield."
